export const sample = '<div>\
<h2>Sample Journal Title</h2>\
<p><strong>Authors:</strong>Brian Chen, Farida, Shaurya Mehta, Parth Khanna</p>\
<h3>Abstract</h3>\
<p><strong>Plasmid Construction</strong></p>\
<p>We used pX330-U6-Chimeric_BB-CBh-hSpCas9 from Feng Zhang (Addgene #42230; Cong et al., 2013) to construct CRISPR/Cas vectors according to the protocol of Ran et al. (Ran et al., 2013). To construct donor plasmids for the expression of OsTIR1 from the AAVS1 locus, AAVS1 hPGK-Puro-pA from Rudolf Jaenisch (Addgene #22072; Hockemeyer et al., 2009) was modified. The CMV and tet promoters from pIRES2-AcGFP (Clontech) and ptet-One (Clontech), respectively, the SV40 terminator from pIRES2-AcGFP, and a codon-optimized OsTIR1 gene were used. The template plasmids shown in Figure S6A were based on pBluescript and constructed using synthesized DNA and genes encoding mClover and mCherry2 from Michael Lin (Addgene #40259; Lam et al., 2012) and Michael Davidson (Addgene #54517), respectively. An experimental overview of the construction of donor vectors is presented in Figure S6B. To construct donor vectors by PCR (Figures 1A and 4A), the template DNA was amplified using Phusion DNA polymerase (New England Biolabs) and 200-base oligonucleotides containing a 175-base homology sequence to the target locus. Amplified DNA was cloned at the EcoRV site of pBluescript or into pCR Blunt II-TOPO (Thermo Fisher Scientific). To construct donor vectors via gene synthesis (Figure 5A), homology arms that were split by the BamHI sequence were synthesized. The mAID-mClover cassette containing a selection marker was excised by BamHI and cloned at the BamHI site, between the homology arms. In all cases, homology arms were designed to introduce a silent mutation or to delete partly the recognition sequence after integration at the target locus, to prevent re-cutting. All plasmids shown in Figure S6A are available from Addgene (https://www.addgene.org) and the Gene Engineering Division of the National Bioresource Project (http://dna.brc.riken.jp).</p>\
<h3>Introduction</h3>\
<p><strong>Plasmid Construction</strong></p>\
<p>We used pX330-U6-Chimeric_BB-CBh-hSpCas9 from Feng Zhang (Addgene #42230; Cong et al., 2013) to construct CRISPR/Cas vectors according to the protocol of Ran et al. (Ran et al., 2013). To construct donor plasmids for the expression of OsTIR1 from the AAVS1 locus, AAVS1 hPGK-Puro-pA from Rudolf Jaenisch (Addgene #22072; Hockemeyer et al., 2009) was modified. The CMV and tet promoters from pIRES2-AcGFP (Clontech) and ptet-One (Clontech), respectively, the SV40 terminator from pIRES2-AcGFP, and a codon-optimized OsTIR1 gene were used. The template plasmids shown in Figure S6A were based on pBluescript and constructed using synthesized DNA and genes encoding mClover and mCherry2 from Michael Lin (Addgene #40259; Lam et al., 2012) and Michael Davidson (Addgene #54517), respectively. An experimental overview of the construction of donor vectors is presented in Figure S6B. To construct donor vectors by PCR (Figures 1A and 4A), the template DNA was amplified using Phusion DNA polymerase (New England Biolabs) and 200-base oligonucleotides containing a 175-base homology sequence to the target locus. Amplified DNA was cloned at the EcoRV site of pBluescript or into pCR Blunt II-TOPO (Thermo Fisher Scientific). To construct donor vectors via gene synthesis (Figure 5A), homology arms that were split by the BamHI sequence were synthesized. The mAID-mClover cassette containing a selection marker was excised by BamHI and cloned at the BamHI site, between the homology arms. In all cases, homology arms were designed to introduce a silent mutation or to delete partly the recognition sequence after integration at the target locus, to prevent re-cutting. All plasmids shown in Figure S6A are available from Addgene (https://www.addgene.org) and the Gene Engineering Division of the National Bioresource Project (http://dna.brc.riken.jp).</p>\
<h3>Related Works</h3>\
<p><strong>Plasmid Construction</strong></p>\
<p>We used pX330-U6-Chimeric_BB-CBh-hSpCas9 from Feng Zhang (Addgene #42230; Cong et al., 2013) to construct CRISPR/Cas vectors according to the protocol of Ran et al. (Ran et al., 2013). To construct donor plasmids for the expression of OsTIR1 from the AAVS1 locus, AAVS1 hPGK-Puro-pA from Rudolf Jaenisch (Addgene #22072; Hockemeyer et al., 2009) was modified. The CMV and tet promoters from pIRES2-AcGFP (Clontech) and ptet-One (Clontech), respectively, the SV40 terminator from pIRES2-AcGFP, and a codon-optimized OsTIR1 gene were used. The template plasmids shown in Figure S6A were based on pBluescript and constructed using synthesized DNA and genes encoding mClover and mCherry2 from Michael Lin (Addgene #40259; Lam et al., 2012) and Michael Davidson (Addgene #54517), respectively. An experimental overview of the construction of donor vectors is presented in Figure S6B. To construct donor vectors by PCR (Figures 1A and 4A), the template DNA was amplified using Phusion DNA polymerase (New England Biolabs) and 200-base oligonucleotides containing a 175-base homology sequence to the target locus. Amplified DNA was cloned at the EcoRV site of pBluescript or into pCR Blunt II-TOPO (Thermo Fisher Scientific). To construct donor vectors via gene synthesis (Figure 5A), homology arms that were split by the BamHI sequence were synthesized. The mAID-mClover cassette containing a selection marker was excised by BamHI and cloned at the BamHI site, between the homology arms. In all cases, homology arms were designed to introduce a silent mutation or to delete partly the recognition sequence after integration at the target locus, to prevent re-cutting. All plasmids shown in Figure S6A are available from Addgene (https://www.addgene.org) and the Gene Engineering Division of the National Bioresource Project (http://dna.brc.riken.jp).</p>\
<h3>Experiments</h3>\
<p><strong>Plasmid Construction</strong></p>\
<p>We used pX330-U6-Chimeric_BB-CBh-hSpCas9 from Feng Zhang (Addgene #42230; Cong et al., 2013) to construct CRISPR/Cas vectors according to the protocol of Ran et al. (Ran et al., 2013). To construct donor plasmids for the expression of OsTIR1 from the AAVS1 locus, AAVS1 hPGK-Puro-pA from Rudolf Jaenisch (Addgene #22072; Hockemeyer et al., 2009) was modified. The CMV and tet promoters from pIRES2-AcGFP (Clontech) and ptet-One (Clontech), respectively, the SV40 terminator from pIRES2-AcGFP, and a codon-optimized OsTIR1 gene were used. The template plasmids shown in Figure S6A were based on pBluescript and constructed using synthesized DNA and genes encoding mClover and mCherry2 from Michael Lin (Addgene #40259; Lam et al., 2012) and Michael Davidson (Addgene #54517), respectively. An experimental overview of the construction of donor vectors is presented in Figure S6B. To construct donor vectors by PCR (Figures 1A and 4A), the template DNA was amplified using Phusion DNA polymerase (New England Biolabs) and 200-base oligonucleotides containing a 175-base homology sequence to the target locus. Amplified DNA was cloned at the EcoRV site of pBluescript or into pCR Blunt II-TOPO (Thermo Fisher Scientific). To construct donor vectors via gene synthesis (Figure 5A), homology arms that were split by the BamHI sequence were synthesized. The mAID-mClover cassette containing a selection marker was excised by BamHI and cloned at the BamHI site, between the homology arms. In all cases, homology arms were designed to introduce a silent mutation or to delete partly the recognition sequence after integration at the target locus, to prevent re-cutting. All plasmids shown in Figure S6A are available from Addgene (https://www.addgene.org) and the Gene Engineering Division of the National Bioresource Project (http://dna.brc.riken.jp).</p>\
<p><strong>Plasmid Construction</strong></p>\
<p>We used pX330-U6-Chimeric_BB-CBh-hSpCas9 from Feng Zhang (Addgene #42230; Cong et al., 2013) to construct CRISPR/Cas vectors according to the protocol of Ran et al. (Ran et al., 2013). To construct donor plasmids for the expression of OsTIR1 from the AAVS1 locus, AAVS1 hPGK-Puro-pA from Rudolf Jaenisch (Addgene #22072; Hockemeyer et al., 2009) was modified. The CMV and tet promoters from pIRES2-AcGFP (Clontech) and ptet-One (Clontech), respectively, the SV40 terminator from pIRES2-AcGFP, and a codon-optimized OsTIR1 gene were used. The template plasmids shown in Figure S6A were based on pBluescript and constructed using synthesized DNA and genes encoding mClover and mCherry2 from Michael Lin (Addgene #40259; Lam et al., 2012) and Michael Davidson (Addgene #54517), respectively. An experimental overview of the construction of donor vectors is presented in Figure S6B. To construct donor vectors by PCR (Figures 1A and 4A), the template DNA was amplified using Phusion DNA polymerase (New England Biolabs) and 200-base oligonucleotides containing a 175-base homology sequence to the target locus. Amplified DNA was cloned at the EcoRV site of pBluescript or into pCR Blunt II-TOPO (Thermo Fisher Scientific). To construct donor vectors via gene synthesis (Figure 5A), homology arms that were split by the BamHI sequence were synthesized. The mAID-mClover cassette containing a selection marker was excised by BamHI and cloned at the BamHI site, between the homology arms. In all cases, homology arms were designed to introduce a silent mutation or to delete partly the recognition sequence after integration at the target locus, to prevent re-cutting. All plasmids shown in Figure S6A are available from Addgene (https://www.addgene.org) and the Gene Engineering Division of the National Bioresource Project (http://dna.brc.riken.jp).</p>\
<h3>Discussion</h3>\
<p><strong>Plasmid Construction</strong></p>\
<p>We used pX330-U6-Chimeric_BB-CBh-hSpCas9 from Feng Zhang (Addgene #42230; Cong et al., 2013) to construct CRISPR/Cas vectors according to the protocol of Ran et al. (Ran et al., 2013). To construct donor plasmids for the expression of OsTIR1 from the AAVS1 locus, AAVS1 hPGK-Puro-pA from Rudolf Jaenisch (Addgene #22072; Hockemeyer et al., 2009) was modified. The CMV and tet promoters from pIRES2-AcGFP (Clontech) and ptet-One (Clontech), respectively, the SV40 terminator from pIRES2-AcGFP, and a codon-optimized OsTIR1 gene were used. The template plasmids shown in Figure S6A were based on pBluescript and constructed using synthesized DNA and genes encoding mClover and mCherry2 from Michael Lin (Addgene #40259; Lam et al., 2012) and Michael Davidson (Addgene #54517), respectively. An experimental overview of the construction of donor vectors is presented in Figure S6B. To construct donor vectors by PCR (Figures 1A and 4A), the template DNA was amplified using Phusion DNA polymerase (New England Biolabs) and 200-base oligonucleotides containing a 175-base homology sequence to the target locus. Amplified DNA was cloned at the EcoRV site of pBluescript or into pCR Blunt II-TOPO (Thermo Fisher Scientific). To construct donor vectors via gene synthesis (Figure 5A), homology arms that were split by the BamHI sequence were synthesized. The mAID-mClover cassette containing a selection marker was excised by BamHI and cloned at the BamHI site, between the homology arms. In all cases, homology arms were designed to introduce a silent mutation or to delete partly the recognition sequence after integration at the target locus, to prevent re-cutting. All plasmids shown in Figure S6A are available from Addgene (https://www.addgene.org) and the Gene Engineering Division of the National Bioresource Project (http://dna.brc.riken.jp).</p>\
<h3>Conclusion</h3>\
<p><strong>Plasmid Construction</strong></p>\
<p>We used pX330-U6-Chimeric_BB-CBh-hSpCas9 from Feng Zhang (Addgene #42230; Cong et al., 2013) to construct CRISPR/Cas vectors according to the protocol of Ran et al. (Ran et al., 2013). To construct donor plasmids for the expression of OsTIR1 from the AAVS1 locus, AAVS1 hPGK-Puro-pA from Rudolf Jaenisch (Addgene #22072; Hockemeyer et al., 2009) was modified. The CMV and tet promoters from pIRES2-AcGFP (Clontech) and ptet-One (Clontech), respectively, the SV40 terminator from pIRES2-AcGFP, and a codon-optimized OsTIR1 gene were used. The template plasmids shown in Figure S6A were based on pBluescript and constructed using synthesized DNA and genes encoding mClover and mCherry2 from Michael Lin (Addgene #40259; Lam et al., 2012) and Michael Davidson (Addgene #54517), respectively. An experimental overview of the construction of donor vectors is presented in Figure S6B. To construct donor vectors by PCR (Figures 1A and 4A), the template DNA was amplified using Phusion DNA polymerase (New England Biolabs) and 200-base oligonucleotides containing a 175-base homology sequence to the target locus. Amplified DNA was cloned at the EcoRV site of pBluescript or into pCR Blunt II-TOPO (Thermo Fisher Scientific). To construct donor vectors via gene synthesis (Figure 5A), homology arms that were split by the BamHI sequence were synthesized. The mAID-mClover cassette containing a selection marker was excised by BamHI and cloned at the BamHI site, between the homology arms. In all cases, homology arms were designed to introduce a silent mutation or to delete partly the recognition sequence after integration at the target locus, to prevent re-cutting. All plasmids shown in Figure S6A are available from Addgene (https://www.addgene.org) and the Gene Engineering Division of the National Bioresource Project (http://dna.brc.riken.jp).</p>\
<h3>References</h3>\
<p>Yagi et al., 1993\
T. Yagi, T. Tokunaga, Y. Furuta, S. Nada, M. Yoshida, T. Tsukada, Y. Saga, N. Takeda, Y. Ikawa, S. Aizawa\
<br>Wang et al., 2015\
T. Wang, K. Birsoy, N.W. Hughes, K.M. Krupczak, Y. Post, J.J. Wei, E.S. Lander, D.M. Sabatini\
Identification and characterization of essential genes in the human genome\
Science, 350 (2015), pp. 1096-1101</p>\
</div>';
